### ISSUE TITLE
Details

### ISSUE THREAD

**Issue by nim65s** [humanoid-path-planner/hpp-statistics#5]
README:
- Version don't match versions in the Releases
- hpp-util is a dependency (https://github.com/humanoid-path-planner/hpp-statistics/blob/master/CMakeLists.txt#L43)
- missing --recursive in git clone

Licence is also missing

**Comment by jmirabel** [comment]
- git link in README should be `https://github.com/humanoid-path-planner/hpp-statistics/issues/5` and not `https://github.com/billx09/hpp-statistics`

Would you mind handling those issues ?
